In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warinings
warnings.filterwarnings("ignore")
from sklearn.cluster import KMeans

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\HP\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\HP\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_14160\542326747.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\HP\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\HP\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\HP\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_14160\542326747.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\HP\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\HP\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\HP\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_14160\542326747.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\HP\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\HP\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\HP\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\HP\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\HP\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\HP\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\HP\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_14160\542326747.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\HP\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\HP\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ModuleNotFoundError: No module named 'warinings'

In [2]:
Univ = pd.read_csv("Universities.csv")
Univ

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [3]:
Univ.describe()

               SAT       Top10     Accept   SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.00000     25.000000  25.000000
mean   1266.440000   76.480000  39.200000  12.72000  27388.000000  86.720000
std     108.359771   19.433905  19.727308   4.06735  14424.883165   9.057778
min    1005.000000   28.000000  14.000000   6.00000   8704.000000  67.000000
25%    1240.000000   74.000000  24.000000  11.00000  15140.000000  81.000000
50%    1285.000000   81.000000  36.000000  12.00000  27553.000000  90.000000
75%    1340.000000   90.000000  50.000000  14.00000  34870.000000  94.000000
max    1415.000000  100.000000  90.000000  25.00000  63575.000000  97.000000

In [4]:
Univ1 = Univ.iloc[:,1:]

In [5]:
Univ1

     SAT  Top10  Accept  SFRatio  Expenses  GradRate
0   1310     89      22       13     22704        94
1   1415    100      25        6     63575        81
2   1260     62      59        9     25026        72
3   1310     76      24       12     31510        88
4   1280     83      33       13     21864        90
5   1340     89      23       10     32162        95
6   1315     90      30       12     31585        95
7   1255     74      24       12     20126        92
8   1400     91      14       11     39525        97
9   1305     75      44        7     58691        87
10  1380     94      30       10     34870        91
11  1260     85      39       11     28052        89
12  1255     81      42       13     15122        94
13  1081     38      54       18     10185        80
14  1375     91      14        8     30220        95
15  1005     28      90       19      9066        69
16  1360     90      20       12     36450        93
17  1075     49      67       25      8704        67
18  1240     95      40       17     15140        78
19  1290     75      50       13     38380        87
20  1180     65      68       16     15470        85
21  1285     80      36       11     27553        90
22  1225     77      44       14     13349        92
23  1085     40      69       15     11857        71
24  1375     95      19       11     43514        96

In [11]:
cols = Univ1.columns

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_Univ_df = pd.DataFrame(scaler.fit_transform(Univ1),columns = cols)
scaled_Univ_df

         SAT     Top10    Accept   SFRatio  Expenses  GradRate
0   0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
1   1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
2  -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
3   0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
4   0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587
5   0.692848  0.657519 -0.838130 -0.682530  0.337780  0.932982
6   0.457378  0.710037 -0.475975 -0.180670  0.296955  0.932982
7  -0.107751 -0.130243 -0.786394 -0.180670 -0.513817  0.594945
8   1.257977  0.762555 -1.303758 -0.431600  0.858743  1.158339
9   0.363190 -0.077726  0.248335 -1.435321  2.214818  0.031550
10  1.069601  0.920107 -0.475975 -0.682530  0.529383  0.482266
11 -0.060657  0.447449 -0.010347 -0.431600  0.046981  0.256908
12 -0.107751  0.237379  0.144862  0.070260 -0.867871  0.820303
13 -1.746625 -2.020875  0.765699  1.324911 -1.217184 -0.757202
14  1.022507  0.762555 -1.303758 -1.184390  0.200376  0.932982
15 -2.462455 -2.546050  2.628211  1.575841 -1.296358 -1.996671
16  0.881224  0.710037 -0.993340 -0.180670  0.641174  0.707624
17 -1.803138 -1.443182  1.438273  3.081422 -1.321971 -2.222029
18 -0.249033  0.972625  0.041389  1.073981 -0.866597 -0.982560
19  0.221907 -0.077726  0.558754  0.070260  0.777730  0.031550
20 -0.814162 -0.602901  1.490010  0.823051 -0.843248 -0.193808
21  0.174813  0.184862 -0.165557 -0.431600  0.011674  0.369587
22 -0.390316  0.027309  0.248335  0.321191 -0.993318  0.594945
23 -1.708950 -1.915840  1.541746  0.572121 -1.098883 -1.771313
24  1.022507  0.972625 -1.045076 -0.431600  1.140982  1.045661

In [13]:
from sklearn.cluster import KMeans
clusters_new = KMeans(3,random_state=0)
clusters_new.fit(scaled_Univ_df)

KMeans(n_clusters=3, random_state=0)

In [14]:
clusters_new.labels_

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1], dtype=int32)

In [15]:
set(clusters_new.labels_)

{np.int32(0), np.int32(1), np.int32(2)}

In [16]:
Univ["clusterid_new"]=clusters_new.labels_

In [17]:
Univ.sort_values(by = "clusterid_new")

,Univ,SAT,Top10,Accept,SFRatio,Expenses,GradRate,clusterid_new
13,PennState,1081,38,54,18,10185,80,0
15,Purdue,1005,28,90,19,9066,69,0
20,UMichigan,1180,65,68,16,15470,85,0
17,TexasA&M,1075,49,67,25,8704,67,0
23,UWisconsin,1085,40,69,15,11857,71,0
6,Duke,1315,90,30,12,31585,95,1
0,Brown,1310,89,22,13,22704,94,1
2,CMU,1260,62,59,9,25026,72,1
12,NotreDame,1255,81,42,13,15122,94,1
7,Georgetown,1255,74,24,12,20126,92,1
8,Harvard,1400,91,14,11,39525,97,1
10,MIT,1380,94,30,10,34870,91,1
14,Princeton,1375,91,14,8,30220,95,1
5,Dartmouth,1340,89,23,10,32162,95,1
3,Columbia,1310,76,24,12,31510,88,1
4,Cornell,1280,83,33,13,21864,90,1
24,Yale,1375,95,19,11,43514,96,1
18,UCBerkeley,1240,95,40,17,15140,78,1
11,Northwestern,1260,85,39,11,28052,89,1
16,Stanford,1360,90,20,12,36450,93,1
19,UChicago,1290,75,50,13,38380,87,1
22,UVA,1225,77,44,14,13349,92,1
21,UPenn,1285,80,36,11,27553,90,1
1,CalTech,1415,100,25,6,63575,81,2
9,JohnsHopkins,1305,75,44,7,58691,87,2

In [18]:
Univ.iloc[:,1:].groupby("clusterid_new").mean()

,SAT,Top10,Accept,SFRatio,Expenses,GradRate
clusterid_new,,,,,,
0,1085.200000,44.000000,69.600000,18.600000,11056.400000,74.400000
1,1306.388889,84.277778,31.277778,11.777778,28175.111111,90.444444
2,1360.000000,87.500000,34.500000,6.500000,61133.000000,84.000000

observations
- cluster 2 apperrs to be the top rated universities cluster as the cut off,score top 10,sf ratio parameter mean values are highest
- cluster 1 appears to occupy the middle level rated universities
- cluster 0 comes as the lower rated universities

In [19]:
Univ[Univ["clusterid_new"]==0]

,Univ,SAT,Top10,Accept,SFRatio,Expenses,GradRate,clusterid_new
13,PennState,1081,38,54,18,10185,80,0
15,Purdue,1005,28,90,19,9066,69,0
17,TexasA&M,1075,49,67,25,8704,67,0
20,UMichigan,1180,65,68,16,15470,85,0
23,UWisconsin,1085,40,69,15,11857,71,0

In [27]:
wcss =[]
for i in range(1,20):
    kmeans = KMeans(n_clusters=i,random_state=0)
    kmeans.fit(scaled_Univ_df)
    wcss.append(kmeans.inertia_)
print(wcss)
plt.plot(range(1,20),wcss)
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylable('WCSS')
plt.show()

TypeError: 'KMeans' object is not callable